### ISSUE TITLE
CloudLAPS: Forbidden, password was not allowed to be updated

### ISSUE THREAD

**Issue by bvalenko** [MSEndpointMgr/CloudLAPS#10]
Also protocolled is source powershell with event-id 403

**Comment by JulesBanana** [comment]
I implemented the solution 5 days ago. The initial PW set was successful. But since then, I receive the same error

**Comment by bvalenko** [comment]
@JulesBanana any update?

**Comment by JulesBanana** [comment]
@bvalenko 

> @JulesBanana I also just ran the powershell with local admin. The result is: password rotation not allowed. Could it might be that the rotation for today already ran thru?

that's correct. I set the rotation to 24 hours and my remediation script runs every day, but not on the same time. If it runs before 24hours, I get the same warning in the event log. If it runs after 24 hours, password rotation will be successful.

**Comment by JulesBanana** [comment]
@RaghuKeenLearner I set the incoming client setting to Allow. 
As I don't know which other settings you changed or which "auto-security-rules" you have in place in your Azure environment, it's really hard to say what needs to be changed in your environment.
I'd recommend to redploy the solution in a new subscription without any rulesets
