### ISSUE TITLE
Please add "Google Compute Engine" when checking if system type is virtual.

### ISSUE THREAD

**Issue by PiKappZ746** [MSEndpointMgr/CloudLAPS#13]
We have Citrix VDI in Google Cloud.  The model for those is reported as "Google Compute Engine".  I would recommend adding that to the $ComputerSystemModel check.

**Comment by NickolajA** [comment]
Thanks for reporting this, I'll make sure that this gets added in the next update that's currently being worked on and should be released shortly.

**Comment by NickolajA** [comment]
Actually, realized this was just in the remediation.ps1 script file, so I updated it just now.
