### ISSUE TITLE
CloudLAPS: Forbidden, password was not allowed to be updated

### ISSUE THREAD

**Issue by jay-7ee** [MSEndpointMgr/CloudLAPS#15]
After the first Password has been set and a local admin account has been created by the script i get the error "CloudLAPS: Forbidden, password was not allowed to be updated".

These are the invocation details for the first run of the "SetSecret" Function in Azure (i redacted all IDs with xxxx):
_2022-01-10 14:00:29.749
Executing 'Functions.SetSecret' (Reason='This function was programmatically called via the host APIs.', Id=xxxx)
Information
2022-01-10 14:00:41.498
WARNING: INITIALIZATION: Fallback context save mode to process because of error during checking token cache persistence: Could not find file 'C:\home\site\wwwroot\.IdentityService'..
Warning
2022-01-10 14:00:44.907
OUTPUT:
Information
2022-01-10 14:00:45.611
OUTPUT: Account SubscriptionName TenantId Environment
Information
2022-01-10 14:00:45.612
OUTPUT: ------- ---------------- -------- -----------
Information
2022-01-10 14:00:45.614
OUTPUT: MSI@xxxx AzureCloud
Information
2022-01-10 14:00:45.614
OUTPUT:
Information
2022-01-10 14:00:45.736
OUTPUT: Inbound request from IP: xxxx
Information
2022-01-10 14:00:45.994
OUTPUT: Header validation succeeded for 'DeviceName' with value: DESKTOP-6CRNDFQ
Information
2022-01-10 14:00:45.996
OUTPUT: Header validation succeeded for 'DeviceID' with value: xxxx
Information
2022-01-10 14:00:45.996
OUTPUT: Header validation succeeded for 'SerialNumber' with value: xxxx
Information
2022-01-10 14:00:45.996
OUTPUT: Header validation succeeded for 'Type' with value: VM
Information
2022-01-10 14:00:46.002
OUTPUT: Header validation succeeded for 'Signature' with value: <redacted>
Information
2022-01-10 14:00:46.015
OUTPUT: Header validation succeeded for 'Thumbprint' with value: xxxx
Information
2022-01-10 14:00:46.052
OUTPUT: Header validation succeeded for 'PublicKey' with value: <redacted>
Information
2022-01-10 14:00:46.052
OUTPUT: Header validation succeeded for 'ContentType' with value: Local Administrator
Information
2022-01-10 14:00:46.052
OUTPUT: Header validation succeeded for 'UserName' with value: LocalAdmin
Information
2022-01-10 14:00:46.052
OUTPUT: Initiating request handling for device named as 'DESKTOP-6CRNDFQ' with identifier: xxxx
Information
2022-01-10 14:00:46.159
OUTPUT: Found trusted Azure AD device record with object identifier: xxxx
Information
2022-01-10 14:00:46.198
OUTPUT: Successfully validated certificate thumbprint from inbound request
Information
2022-01-10 14:00:46.213
OUTPUT: Successfully validated certificate SHA256 hash value from inbound request
Information
2022-01-10 14:00:46.395
OUTPUT: Successfully validated inbound request came from a trusted Azure AD device record
Information
2022-01-10 14:00:46.396
OUTPUT: Azure AD device record was validated as enabled
Information
2022-01-10 14:00:46.396
OUTPUT: Attempting to retrieve secret from vault with name: DESKTOP-6CRNDFQ
Information
2022-01-10 14:00:52.833
OUTPUT: Existing secret was not found, secret update will be allowed
Information
2022-01-10 14:00:58.557
OUTPUT: Attempting to commit secret with name 'DESKTOP-6CRNDFQ' to vault
Information
2022-01-10 14:00:58.965
OUTPUT:
Information
2022-01-10 14:00:58.969
OUTPUT: Vault Name : dodev-cloudlapskeyvault
Information
2022-01-10 14:00:58.970
OUTPUT: Name : DESKTOP-6CRNDFQ
Information
2022-01-10 14:00:58.970
OUTPUT: Version : 795de2acb79642e293db68588ccd588f
Information
2022-01-10 14:00:58.971
OUTPUT: Id : https://xxxx
Information
2022-01-10 14:00:58.971
OUTPUT: Enabled : True
Information
2022-01-10 14:00:58.972
OUTPUT: Expires :
Information
2022-01-10 14:00:58.973
OUTPUT: Not Before :
Information
2022-01-10 14:00:58.973
OUTPUT: Created : 1/10/2022 2:00:58 PM
Information
2022-01-10 14:00:58.974
OUTPUT: Updated : 1/10/2022 2:00:58 PM
Information
2022-01-10 14:00:58.974
OUTPUT: Content Type : Local Administrator
Information
2022-01-10 14:00:58.975
OUTPUT: Tags : Name Value
Information
2022-01-10 14:00:58.975
OUTPUT: DeviceName DESKTOP-6CRNDFQ
Information
2022-01-10 14:00:58.976
OUTPUT: AzureADDeviceID xxxx
Information
2022-01-10 14:00:58.976
OUTPUT: UserName LocalAdmin
Information
2022-01-10 14:00:58.977
OUTPUT:
Information
2022-01-10 14:00:58.977
OUTPUT:
Information
2022-01-10 14:00:59.504
OUTPUT: Successfully committed secret to vault
Information
2022-01-10 14:00:59.514
OUTPUT:
Information
2022-01-10 14:00:59.535
Executed 'Functions.SetSecret' (Succeeded, Id=xxxx, Duration=29802ms)
Information_

For the second run (i redacted all IDs with xxxx):
_2022-01-11 13:00:21.508
Executing 'Functions.SetSecret' (Reason='This function was programmatically called via the host APIs.', Id=xxxx)
Information
2022-01-11 13:00:36.446
WARNING: INITIALIZATION: Fallback context save mode to process because of error during checking token cache persistence: Could not find file 'C:\home\site\wwwroot\.IdentityService'..
Warning
2022-01-11 13:00:41.254
OUTPUT:
Information
2022-01-11 13:00:41.583
OUTPUT: Account SubscriptionName TenantId Environment
Information
2022-01-11 13:00:41.584
OUTPUT: ------- ---------------- -------- -----------
Information
2022-01-11 13:00:41.587
OUTPUT: MSI@xxxx AzureCloud
Information
2022-01-11 13:00:41.587
OUTPUT:
Information
2022-01-11 13:00:41.767
OUTPUT: Inbound request from IP: xxxx
Information
2022-01-11 13:00:42.117
OUTPUT: Header validation succeeded for 'DeviceName' with value: DESKTOP-6CRNDFQ
Information
2022-01-11 13:00:42.118
OUTPUT: Header validation succeeded for 'DeviceID' with value: xxxx
Information
2022-01-11 13:00:42.119
OUTPUT: Header validation succeeded for 'SerialNumber' with value: xxxx
Information
2022-01-11 13:00:42.119
OUTPUT: Header validation succeeded for 'Type' with value: VM
Information
2022-01-11 13:00:42.127
OUTPUT: Header validation succeeded for 'Signature' with value: <redacted>
Information
2022-01-11 13:00:42.128
OUTPUT: Header validation succeeded for 'Thumbprint' with value: xxxx
Information
2022-01-11 13:00:42.147
OUTPUT: Header validation succeeded for 'PublicKey' with value: <redacted>
Information
2022-01-11 13:00:42.147
OUTPUT: Header validation succeeded for 'ContentType' with value: Local Administrator
Information
2022-01-11 13:00:42.147
OUTPUT: Header validation succeeded for 'UserName' with value: LocalAdmin
Information
2022-01-11 13:00:42.147
OUTPUT: Initiating request handling for device named as 'DESKTOP-6CRNDFQ' with identifier: xxxx
Information
2022-01-11 13:00:42.322
OUTPUT: Found trusted Azure AD device record with object identifier: xxxx
Information
2022-01-11 13:00:42.374
OUTPUT: Successfully validated certificate thumbprint from inbound request
Information
2022-01-11 13:00:42.394
OUTPUT: Successfully validated certificate SHA256 hash value from inbound request
Information
2022-01-11 13:00:42.619
OUTPUT: Successfully validated inbound request came from a trusted Azure AD device record
Information
2022-01-11 13:00:42.621
OUTPUT: Azure AD device record was validated as enabled
Information
2022-01-11 13:00:42.622
OUTPUT: Attempting to retrieve secret from vault with name: DESKTOP-6CRNDFQ
Information
2022-01-11 13:00:49.814
OUTPUT: Existing secret was last updated on (UTC): 2022-01-10 14:00:58
Information
2022-01-11 13:00:49.824
OUTPUT: Secret update will be allowed first after (UTC): 2022-01-13 14:00:58
Information
2022-01-11 13:00:49.858
Executed 'Functions.SetSecret' (Succeeded, Id=xxxx, Duration=28371ms)
Information_

**Comment by pryan56** [comment]
I am having a similar issue. I already have a local admin account on the pc and am trying to update this account's password with the CloudLAPS solution. When the Remediation script runs on the device I am getting the following error: "Forbidden, password was not allowed to be updated."

**Comment by pryan56** [comment]
@jay-7ee I was able to figure out what was going on. That warning just means that the password is not allowed to be updated yet since the last updated date (2022-01-10 14:00:58) is not greater than the allowed update date ( 2022-01-13 14:00:58). You can toggle this setting from the default UpdateFrequencyDays value (3 days) to whatever you want. You can change this by going to the function app -> Settings (Configuration) -> Application Settings -> UpdateFrequencyDays. I think it is best practice to set the schedule of your Proactive Remediation script to occur less frequently than your password expiry date. This will stop you from getting these somewhat confusing Warning errors.

**Comment by jay-7ee** [comment]
@pryan56 Thank you very much for pointing that out. It does seem like this was the cause of the error. I've set the UpdateFrequencyDays to 1 and will continue my tests. 
I'am just wondering why the whole function and script seems to be created with the frequency of password changes beeing days (in this case even 3 although it states in the documentation to set the script intervall to 1 day). Does anynone know why the function/script is not intended to be used for smaller intervalls (like e.g. 4 hours)?

**Comment by pryan56** [comment]
@jay-7ee You can set the UpdateFrequencyDays to 0 and it will rotate the password whenever the remediation script is run. In Intune, you could set the schedule to run every 4 hours but I am not sure what you gain rotating that frequently. You would incur more cost doing it that way, as your Azure function would be running very often (especially if you have a large number of devices). Also, it would be an increased amount of transactions to your key vault and other Azure resources. I think that you have to find what works for your organization but for the additional cost, I don't see the security benefit of rotating that often.
