### ISSUE TITLE
CloudLAPS Portal: Search Returned Empty List of Secrets

### ISSUE THREAD

**Issue by USMarine0621** [MSEndpointMgr/CloudLAPS#16]
I am having issues with the CloudLAPS portal, most specifically with returning secrets. My event logs show that the local admin was created and password rotated successfully, with no errors. But in the Intune portal, under device status, the detection status reads: With issues; and I am unable to retreive the secrets from the portal. Any suggestions? Thank you in advance.

**Comment by amitpatel143** [comment]
i am also having same issue 
![image](https://user-images.githubusercontent.com/98168096/150541579-51b3c5f7-9677-426f-b0ee-9c2f07524717.png)

**Comment by USMarine0621** [comment]
Figured out my issue. I was using my device name. I used my serial number from Intune returned secrets.

**Comment by amitpatel143** [comment]
I am using serial number but still same issue
