### ISSUE TITLE
CloudLAPS High Azure Costs

### ISSUE THREAD

**Issue by kmans56** [MSEndpointMgr/CloudLAPS#25]
Has anyone got any comparisons of costs for running this?

Curently seeing really high costs for 40 devices:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/99721717/155183810-4fc69019-042f-48df-b311-836b0db7c553.png">

this is showing the current billing period for 1 month

Any ideas what could cause it or is this expected?

**Comment by RaghuKeenLearner** [comment]
ours is roughly USD $210 for month of Jan for 100+ devices. I think you can change the password rotation freq and that might bring down the cost. Mine is at 1 day.

**Comment by Asaurdiff-Tillamook** [comment]
We are doing testing on CloudLAPS at the moment. This is very concerning since we plan to use this on 800+ devices. Can anyone tell us where the majority of the cost is coming from? 
We are currently in the works on getting billing details for this resource, but not as of yet.

**Comment by JankeSkanke** [comment]
The cost is mainly driven by the Azure function plan you choose vs Number of executions. If you only have a small number of devices you could look into the consumption plan instead of Premium plans. On the Consumption plan, instances of the Functions host are dynamically added and removed based on the number of incoming events.
✔ Pay only when your functions are running.

Have a look here for more information about the plans: 
[https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale](https://docs.microsoft.com/en-us/azure/azure-functions/functions-scale?WT.mc_id=EM-MVP-5002085)

**Comment by kmans56** [comment]
Thats great, just recreated it all in a consumption tier and running at about 1/3 of the costs

**Comment by SWGEZ** [comment]
> Thats great, just recreated it all in a consumption tier and running at about 1/3 of the costs

HOW?!?!?!

**Comment by kmans56** [comment]
Hey @SWGEZ 

You need to create a new resource group and set everything up from scratch, when filling in the names of the resources there is a section that asks for the plan to install onto and you need to select y1 from memory.

I did the below to ensure i didn't lose access to the current machines I had deployed to:
1. Create new RG and deploy solution to this - make sure you check the app plan is set to the lowest
2. change the scripts you are using for detection and remediation Intune
3. ensure this has run against all of your devices after a few days
4. delete the old RG 

And that should see you right, I'm forecasting around £45 instead of the original £170+

Hope that helps

**Comment by SWGEZ** [comment]
Thank you @kmans56 !!! I was stuck in a loop of microsoft documentation and getting no where fast... I could not find where it was to set or change this off the premium plan. I think this has me on the right track to redeploy this...

**Comment by kmans56** [comment]
Yeah the Microsoft docs don't make it very clear but you cant switch down from a premium plan down to consumption it has to be redeployed, glad I could help
