### ISSUE TITLE
Restrict the local administrator password search in the portal.

### ISSUE THREAD

**Issue by Rahmsan** [MSEndpointMgr/CloudLAPS#41]
More of an idea then an issue:

Anyway to restrict the search function in the portal, so that the users are only able to search for devices that they are for example primary user of?

The search function in the portal seems to do a get using an API to receive the secret.
In the workspace logs, the action seems to be called "SecretGet" anyone happen to know where this query/code can be found?

**Comment by NickolajA** [comment]
While I understand the request, I'd recommend that you do not allow regular users access to the portal, it sort of goes against the whole point of "LAPS" in my opinion. It's not a "JIT elevation" solution for regular users. It's meant for rotating the local administrator password for helpdesk or administrators when access is required.

The code for the audit event in the CloudLAPS_Audit custom log are embedded in the portal source code.
