### ISSUE TITLE
granularity access control

### ISSUE THREAD

**Issue by nashein** [MSEndpointMgr/CloudLAPS#45]
Hi guys,

1. Is there a way to granularity access control like we have it on on-prem LAPS? 
f.e. We want to give access Helpdesk from Brazil only to brazil devices - that's possible using standard LAPS.

2. What drove you and why to create such a great solution? 

Cheers :)

**Comment by NickolajA** [comment]
As of right now, we have no plans on extending with such types of "geo" restrictions.
