### ISSUE TITLE
Deploy CloudLAPS to Azure Error: "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by jbeck71380** [MSEndpointMgr/CloudLAPS#46]
Hi there!

I was attempting to deploy cloud laps using the "Deploy to Azure" button as listed in the documentation. However I am running into an error that is preventing me from deploying. 
![image](https://user-images.githubusercontent.com/107489486/186457650-bd20a7dc-be9a-47f1-aa5a-bf234213609d.png)

Any ideas on what could be causing this? 

Thanks for any assistance!

**Comment by Espen94** [comment]
Hi!
I have same issue when i try to deploy, seems like setup is outdated or broke atm.

**Comment by JankeSkanke** [comment]
This is a known issue at the moment. We are working on a fix. 
Ping @NickolajA

**Comment by NickolajA** [comment]
It's being investigated as to what have changed on the Azure side of things since the bicep code has not been touched for several months. We'll update here once we have resolved the issue.

**Comment by NickolajA** [comment]
Problem should have been resolved now. I just did a test deployment and it completed successfully. Thanks to Sandy who found the missing property that needed to be added for the plans.

**Comment by jbeck71380** [comment]
Big thank you for finding this issue and resolving it so quickly. I had been in communication with Microsoft support all last week trying to troubleshoot this issue and was super stuck. However the deployment is now working correctly!

Once again, big thank you!

**Comment by JankeSkanke** [comment]
Big shout out to @sandytsang
