### ISSUE TITLE
Windows365 Issues

### ISSUE THREAD

**Issue by ueliz** [MSEndpointMgr/CloudLAPS#56]
Hi There,

Is there a possibility that CloudLAPS is not working if the VM is based on Windows365?
I tried now all i know but even completely new provisioned CloudPCs  from new users (not reprovisioned) are not able to connect to the Function app
403 forbidden. 
while physical devices seems to work fine.
Any Idea what i do wrong, the CloudPC devices are added to a dynamic Computer Group and the CloudLAPS Event entries exist, means the Remediation Script actually tries to connect and reset but with 403 forbidden.
BR

**Comment by JankeSkanke** [comment]
Make sure you use the latest Proactive remediation script. There was a bug on CloudPC that should have been fixed now.
