### ISSUE TITLE
EventID 15 - Bad Request

### ISSUE THREAD

**Issue by jbeck71380** [MSEndpointMgr/CloudLAPS#61]
Hello,

I am having some trouble after reimaged a PC that was working with CloudLAPS. My issue is that this computer keeps failing with error code 15 - Bad Request. Here is what I have done already:

1) Wiped the stored credential from the ClouldLAPS web vault. I did this manually. There are no credentials stored for this computer any more. This changed the error code from "password rotation not allowed" to "Error 15 - Bad Request".
- As a note I did not purge the key, only deleted it. 

2) Checked the local logs on the device and found Error 15 - Bad Request. No further information was in the local logs.
3) Found the failed request within the monitor section of the CloudLAPS Function App on Azure. (this also didn't provide anything that indicated what was wrong. The request seemed like other requests that were successful.)

I am lost on what to do next. I can just try wiping the device again and reimaging. As a side note - other devices are working normally. No issues with any other device. 

Any ideas?

**Comment by jbeck71380** [comment]
In case anyone else comes across this: you must PURGE the key from the vault. Simply deleting the key will not work. Azure thinks that your trying to update the deleted secret instead of creating a new secret. Go to your CloudLAPS key vault give yourself permission to view secrets inside the key vault and permissions to purge the deleted secrets. After you have given yourself permissions, find the secret and delete the key. After the key is deleted, purge the key under "manage deleted secrets". Restart your computer and let CloudLAPS run again to properly onboard the device.  

Make sure to remove permissions to from the key vault once your done :)

**Comment by Sunyix11** [comment]
Hi,

Unfortunately, we have the same issue. (Event ID15 BadRequest, failed to update password)
We tried to perform your solution, but we did not find any key in the vault. (We added all permission to our ID as you suggested)
Do you have any other solution for this issue? Or do you have any idea why we do not find any key?
