### ISSUE TITLE
Can CloudLAPS have a complexity requirement?

### ISSUE THREAD

**Issue by PatsGithu8** [MSEndpointMgr/CloudLAPS#76]
Hi
I am sure someone has run into this but we've only just run into this recently 
Our intune policy has a local password complexity requirement that must include :
1 upper case letter
1 lower case letter
1 number
and a total of 8 characters ( could be more but lets say 8 as my memory is bad)

We had one device rotate their cloudlaps password and it didnt meet requirements due to having only letters ( pretty rare )
Is there a way to enforce cloudlaps password rotations to have the above complexity requirements?

**Comment by JankeSkanke** [comment]
You should move to Windows LAPS, which is a native solution in Entra ID / Intune. This solution is no longer being maintained since MS now has a native solution. 

https://learn.microsoft.com/en-us/windows-server/identity/laps/laps-overview
