### ISSUE TITLE
Pricing tier does not match the subscription

### ISSUE THREAD

**Issue by mastersoho** [MSEndpointMgr/CloudLAPS#8]
The rest of the workloads deploy from the custom template except for the LA workspace with an error message "pricing tier does not match the subscription". Have logged a ticket with Azure support as well.

**Comment by jnyc** [comment]
I am going through the same thing.   I am using a Pay-as-you go in order to test this out.  Not sure if you need a P1 / P2 Subscription.

**Comment by korniienkoalexis** [comment]
I have the same issue when deploying from the template, I have "Pay-as-you-go" subscription and Enterprise Mobility + Security E5

**Comment by NickolajA** [comment]
PerGB2018 was changed in the bicep file some time ago, closing.
